### ISSUE TITLE
`watch_blocks` function might not behave as expected

### ISSUE THREAD

**Issue by elichai** [scrtlabs/enigma-core#127]
@fredfortier is the purpose of `max_epoch` is that if specified it will stop after it and if not it will loop forever?

if so then this function *will* stop when overflown.
if not then please explain what this parameter is doing exactly.

https://github.com/enigmampc/enigma-core/blob/develop/enigma-principal/app/src/boot_network/principal_utils.rs#L24-L57

Thanks.

**Comment by fredfortier** [comment]
These scalar variables were already there so Isan might be able to elaborate on the exact rationale. From what I understand, he included this to be able to run tests with a finite duration. In production, this should be set to 0. 

I agree that a memory overflow theoretically prohibits the program from running indefinitely. I understand that `unit` is a 64-bit unsigned (not sure if SGX supports 32-bit architectures), so it does not seem like overflow is possible in practice. At the very least, it would first overflow here: `let curr_block = block_number.low_u64() as usize;`. I'm happy to refactor this function to use `U256` instead of scalar types if you have reasons to believe otherwise.

**Comment by elichai** [comment]
If I understand correctly this code should run forever, right? If so it would overflow pretty quickly...
I would just put the increments in the `if` so if the `max_epochs` is zero the `epoch_counter` won't get incremented.

**Comment by AvishaiW** [comment]
@fredfortier what is the status of this issue? is this a change you are considering? I would be happy to hear your thoughts on it. Thanks!

**Comment by fredfortier** [comment]
I didn't write this particular code, and my understanding is that this uint variable is assigned a 64-bit memory address which is enough to count epochs without risking overflow. But I think that suggested change is safe and would save an unnecessary instruction.
